#!/bin/bash

clear

# Check if clean is enabled
# If so, wipe previously generated slimes (DOESN'T AFFECT DB!)
if [[ "$BASH_ARGV" = "c" ]]; then
	rm -fr './slimes'
	mkdir './slimes'
fi

# Verify slime folder exists
if [[ ! -d "./slimes" ]]; then
	mkdir './slimes'
fi

# Run the bot in a specific mode
if [[ "$1" = "gen" ]]; then
	# Check if gen count is provided
	re='^[0-9]+$'
	if [[ $2 =~ $re ]]; then
		python bot.py $1 $2
	else
		python bot.py $1
	fi
elif [[ "$1" = "bot" ]];then
	python bot.py
fi